### ISSUE TITLE
Error: Cannot find module mode-comparison.js

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionicons#624]
```
C:\ae\aedev\ionicons>npm run mode.comparison

> ionicons@4.4.4 mode.comparison C:\ae\aedev\ionicons
> node scripts/mode-comparison.js

module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\ae\aedev\ionicons\scripts\mode-comparison.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionicons@4.4.4 mode.comparison: `node scripts/mode-comparison.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionicons@4.4.4 mode.comparison script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peter\AppData\Roaming\npm-cache\_logs\2018-10-13T04_16_29_354Z-debug.log

C:\ae\aedev\ionicons>
```

![capture416](https://user-images.githubusercontent.com/140737/46901328-37072000-ce66-11e8-8460-4033806fd092.png)

**Comment by liamdebeasi** [comment]
Thanks for the issue and apologies for the delay. I am going to close as we no longer use this build process. Additionally, Ionicons uses SVG data instead of icon fonts.
